name: taxi_rides_hourly_features_pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_feature_pipeline.txt  # Install dependencies if a requirements file exists
        
      - name: Debugging Check if API key is loaded
        run: |
          echo "HOPSWORKS_API_KEY is loaded: ${{ secrets.HOPSWORKS_API_KEY }}" # Don't print actual key for security, just checking if it's loaded.

      - name: Run new data fetch pipeline and load to Hopsworks
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}/src  # Adjust PYTHONPATH to point to the src folder
        run: python -m feature_pipeline  # Run the module from the root of your repository
